project_name: webmesh

before:
  hooks:
    - go mod tidy
    - make generate

builds:
  - id: app
    main: cmd/app/main.go
    binary: app
    tags:
      - osusergo
      - netgo
    flags:
      - -trimpath
    ldflags:
      - -s -w 
      - -X github.com/kvdi/kvdi/pkg/version.Version={{ .Env.VERSION }}
      - -X github.com/kvdi/kvdi/pkg/version.Commit={{ .Commit }}
      - -X github.com/kvdi/kvdi/pkg/version.BuildDate={{ .Date }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
     - CGO_ENABLED=0

  - id: manager
    main: cmd/manager/main.go
    binary: manager
    tags:
      - osusergo
      - netgo
    flags:
      - -trimpath
    ldflags:
      - -s -w 
      - -X github.com/kvdi/kvdi/pkg/version.Version={{ .Env.VERSION }}
      - -X github.com/kvdi/kvdi/pkg/version.Commit={{ .Commit }}
      - -X github.com/kvdi/kvdi/pkg/version.BuildDate={{ .Date }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
     - CGO_ENABLED=0

  - id: proxy
    main: cmd/kvdi-proxy/main.go
    binary: proxy
    tags:
      - netgo
    flags:
      - -trimpath
    ldflags:
      - -s -w 
      - -X github.com/kvdi/kvdi/pkg/version.Version={{ .Env.VERSION }}
      - -X github.com/kvdi/kvdi/pkg/version.Commit={{ .Commit }}
      - -X github.com/kvdi/kvdi/pkg/version.BuildDate={{ .Date }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
     - >-
      CGO_ENABLED=1
      {{ if eq .Arch "arm64" }}
      CC=${PWD}/bin/toolchains/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
      CXX=${PWD}/bin/toolchains/aarch64-linux-musl-cross/bin/aarch64-linux-musl-g++
      {{ else if eq .Arch "amd64" }}
      CC=${PWD}/bin/toolchains/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc
      CXX=${PWD}/bin/toolchains/x86_64-linux-musl-cross/bin/x86_64-linux-musl-g++
      {{ end }}


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
