project_name: webmesh

before:
  hooks:
    - go mod tidy
    - make generate

builds:
  - id: app
    main: cmd/app/main.go
    binary: app
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/kvdi/kvdi/pkg/version.Version={{.Version}}
      - -X github.com/kvdi/kvdi/pkg/version.Commit={{.Commit}}
      - -X github.com/kvdi/kvdi/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
     - CGO_ENABLED=1
    overrides:
      - goarch: arm64
        env:
          - >-
            CGO_ENABLED=1
            CC=${PWD}/bin/toolchains/arm-linux-musleabi-cross/bin/aarch64-linux-musleabi-gcc
            CXX=${PWD}/bin/toolchains/arm-linux-musleabi-cross/bin/aarch64-linux-musleabi-g++
      - goarch: amd64
        env:
          - CGO_ENABLED=1
            CC=${PWD}/bin/toolchains/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc
            CXX=${PWD}/bin/toolchains/x86_64-linux-musl-cross/bin/x86_64-linux-musl-g++

  - id: manager
    main: cmd/manager/main.go
    binary: manager
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/kvdi/kvdi/pkg/version.Version={{.Version}}
      - -X github.com/kvdi/kvdi/pkg/version.Commit={{.Commit}}
      - -X github.com/kvdi/kvdi/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
     - CGO_ENABLED=1
    overrides:
      - goarch: arm64
        env:
          - >-
            CGO_ENABLED=1
            CC=${PWD}/bin/toolchains/arm-linux-musleabi-cross/bin/aarch64-linux-musleabi-gcc
            CXX=${PWD}/bin/toolchains/arm-linux-musleabi-cross/bin/aarch64-linux-musleabi-g++
      - goarch: amd64
        env:
          - CGO_ENABLED=1
            CC=${PWD}/bin/toolchains/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc
            CXX=${PWD}/bin/toolchains/x86_64-linux-musl-cross/bin/x86_64-linux-musl-g++

  - id: proxy
    main: cmd/kvdi-proxy/main.go
    binary: proxy
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/kvdi/kvdi/pkg/version.Version={{.Version}}
      - -X github.com/kvdi/kvdi/pkg/version.Commit={{.Commit}}
      - -X github.com/kvdi/kvdi/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
     - CGO_ENABLED=1
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - >-
            CGO_ENABLED=1
            CC=${PWD}/bin/toolchains/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
      - goos: linux
        goarch: amd64
        env:
          - >-
            CGO_ENABLED=1
            CC=${PWD}/bin/toolchains/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj