name: Desktops

on:
  push:
    branches: [main]

env:
  PLATFORMS: linux/amd64,linux/arm64
  IMAGE_PREFIX: ghcr.io/webmeshproj/desktop

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get image version
        shell: bash
        run: |
          echo ::set-output name=tag::$([[ "${GITHUB_REF##*/}" == "main" ]] && echo latest || echo ${GITHUB_REF##*/})
        id: version

      - name: Login to GHCR
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Ubuntu Base Image
        uses: docker/build-push-action@v5
        id: ubuntu-base
        with:
          context: build/desktops/ubuntu
          file: Dockerfile.base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_PREFIX }}-ubuntu-base:${{ steps.version.outputs.tag }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}-ubuntu-base:${{ steps.version.outputs.tag }}
          cache-to: type=inline

      - name: Build App Base Image
        uses: docker/build-push-action@v5
        id: app-base
        with:
          context: build/desktops/app-profiles
          file: Dockerfile.base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_PREFIX }}-apps-base:${{ steps.version.outputs.tag }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}-apps-base:${{ steps.version.outputs.tag }}
          cache-to: type=inline

      - name: Build DOSBox Image
        uses: docker/build-push-action@v5
        id: dosbox
        with:
          context: build/desktops/dosbox
          file: Dockerfile.base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_PREFIX }}-dosbox:${{ steps.version.outputs.tag }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}-dosbox:${{ steps.version.outputs.tag }}
          cache-to: type=inline

      - name: Build Ubuntu XFCE Image
        uses: docker/build-push-action@v5
        id: ubuntu-xfce4
        with:
          context: build/desktops/ubuntu
          file: Dockerfile.desktop
          build-args: |
            BASE_IMAGE=${{ steps.ubuntu-base.outputs.digest }}
            DESKTOP_PACKAGE=xfce4
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_PREFIX }}-ubuntu-base:${{ steps.version.outputs.tag }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}-ubuntu-base:${{ steps.version.outputs.tag }}
          cache-to: type=inline
