name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build test image
        run: |
          make test-docker-build

      - name: Lint all packages
        run: |
          make lint-in-docker

      - name: Run all unit tests
        run: |
          make test-in-docker
