name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Tests
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
          cache: false

      - name: Static Analysis
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          args: --timeout 10m
          skip-cache: true
          skip-pkg-cache: true

      - name: Unit Tests
        run: make test
